//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Parser\Sigma16.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISigma16Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Sigma16BaseListener : ISigma16Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] Sigma16Parser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] Sigma16Parser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] Sigma16Parser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] Sigma16Parser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.rrr_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRrr_instruction([NotNull] Sigma16Parser.Rrr_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.rrr_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRrr_instruction([NotNull] Sigma16Parser.Rrr_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.rx_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRx_instruction([NotNull] Sigma16Parser.Rx_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.rx_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRx_instruction([NotNull] Sigma16Parser.Rx_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.x_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterX_instruction([NotNull] Sigma16Parser.X_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.x_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitX_instruction([NotNull] Sigma16Parser.X_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.data_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_instruction([NotNull] Sigma16Parser.Data_instructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.data_instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_instruction([NotNull] Sigma16Parser.Data_instructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.label_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel_def([NotNull] Sigma16Parser.Label_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.label_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel_def([NotNull] Sigma16Parser.Label_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] Sigma16Parser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] Sigma16Parser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.displacement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplacement([NotNull] Sigma16Parser.DisplacementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.displacement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplacement([NotNull] Sigma16Parser.DisplacementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.rrr_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRrr_command([NotNull] Sigma16Parser.Rrr_commandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.rrr_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRrr_command([NotNull] Sigma16Parser.Rrr_commandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.rx_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRx_command([NotNull] Sigma16Parser.Rx_commandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.rx_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRx_command([NotNull] Sigma16Parser.Rx_commandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Sigma16Parser.x_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterX_command([NotNull] Sigma16Parser.X_commandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Sigma16Parser.x_command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitX_command([NotNull] Sigma16Parser.X_commandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
